version: '2.1'
services:
  qwc-qgis-server:
    build:
      context: ./qgis-server
      args:
        - URL_PREFIX=/ows
    ports:
     - "127.0.0.1:8001:80"
    volumes:
      - ./volumes/qgs-resources:/data:ro
      - ./volumes/geodata:/geodata:ro

  qwc-config-service:
    build:
      context: ./wsgi-service
      args:
        - SERVICE=qwc-config-service
    environment:
      - QWC2_THEMES_CONFIG=/data/themesConfig.json
      - QGIS_SERVER_URL=http://qwc-qgis-server/ows/
      - FLASK_DEBUG=1
    ports:
      - "127.0.0.1:5010:9090"
    volumes:
      - ./volumes/qgs-resources:/data

  qwc-ogc-service:
    build:
      context: ./wsgi-service
      args:
        - SERVICE=qwc-ogc-service
        - SERVICE_MOUNTPOINT=/ows
    environment:
      - CONFIG_SERVICE_URL=http://qwc-config-service:9090/
      - QGIS_SERVER_URL=http://qwc-qgis-server/ows/
    ports:
      - "127.0.0.1:5013:9090"
    depends_on:
      - qwc-qgis-server
      - qwc-config-service

  qwc-api-gateway:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
