version: '2.1'
services:
  qwc-postgis:
    build:
      context: ./postgis
#      args:
#        - ALEMBIC_VERSION=56846d9f2753
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
    ports:
     - "127.0.0.1:5439:5432"

  qwc-qgis-server:
    build:
      context: ./qgis-server
      args:
        - URL_PREFIX=/ows
    ports:
     - "127.0.0.1:8001:80"
    volumes:
      - ./volumes/qgs-resources:/data:ro
      - ./volumes/geodata:/geodata:ro

  qwc-config-service:
    build:
      context: ./wsgi-service
      args:
        - SERVICE=qwc-config-service
    environment:
      - QGIS_SERVER_URL=http://qwc-qgis-server/ows/
      - QWC2_PATH=/qwc2/
      - QWC2_THEMES_CONFIG=/qwc2/themesConfig.json
      - FLASK_DEBUG=1
    ports:
      - "127.0.0.1:5010:9090"
    volumes:
      - ./volumes/qgs-resources:/data
      - ./volumes/qwc2:/qwc2

  qwc-ogc-service:
    build:
      context: ./wsgi-service
      args:
        - SERVICE=qwc-ogc-service
        - SERVICE_MOUNTPOINT=/ows
    environment:
      - CONFIG_SERVICE_URL=http://qwc-config-service:9090/
      - QGIS_SERVER_URL=http://qwc-qgis-server/ows/
    ports:
      - "127.0.0.1:5013:9090"
    depends_on:
      - qwc-qgis-server
      - qwc-config-service

  qwc-map-viewer:
    build:
      context: ./wsgi-service
      args:
        - SERVICE=qwc-map-viewer
    environment:
      - CONFIG_SERVICE_URL=http://qwc-config-service:9090/
      - QWC2_PATH=/qwc2/
      - QWC2_CONFIG=/qwc2/config.json
      - OGC_SERVICE_URL=/ows/
    ports:
      - "127.0.0.1:5030:9090"
    volumes:
      - ./volumes/qwc2:/qwc2:ro
    depends_on:
      - qwc-config-service
      - qwc-ogc-service

  qwc-api-gateway:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
